### ISSUE TITLE
About the time partial derivative in Lagrangian

### ISSUE THREAD

**Issue by RequieMa** [assumptionsofphysics/book#10]
Hi @gcarcassi,

I am impressed by your goal and this on-going work. I'd like to help. 

I just begin to read the latest draft and get a bit confused here. 
![image](https://github.com/user-attachments/assets/695d73ca-6533-484c-88fd-6daf42d384d3)

Previously, you stated the Lagrangian to be L(x, v, t), in its most general form. Then shouldn't the Euler-Lagrange equations apply this general form of L? If that is the case, then shouldn't the first line here plus a partial derivative w.r.t time as well?

**Comment by gcarcassi** [comment]
I think you are right: we should add the partial derivative of parial_v L in time. The result remains the same. I don't see any other derivative in time needed for the rest of the section, so that should be the only change?

**Comment by RequieMa** [comment]
I only read to this part. I will continue read it to see if there are other parts to change. Are you going to change it, or should I make a pull request?

**Comment by RequieMa** [comment]
![image](https://github.com/user-attachments/assets/78efae13-8651-4e6c-812f-14e67c514c4c)
Same for Hamiltonian

**Comment by gcarcassi** [comment]
Modified the equations to:
![image](https://github.com/user-attachments/assets/9e29c4dc-6de2-4e50-89d1-dd2d0dd08149)
and
![image](https://github.com/user-attachments/assets/0fe5e8c0-4153-4f54-8dfa-cae7454f053e)
