### ISSUE TITLE
On page 11, the comparison between Lagrangian and Hamiltonian

### ISSUE THREAD

**Issue by RequieMa** [assumptionsofphysics/book#11]
![image](https://github.com/user-attachments/assets/fb166c06-14e2-47ce-b1cc-39b2605d206e)

I think that for this part you meant "whether we can write the Lagrangian in terms of position and **momentum** and the Hamiltonian in terms of position and **velocity**", right?

**Comment by gcarcassi** [comment]
Text is right like that: the expression always allows to write one in terms of the other, but you may not be able to change variables.

**Comment by RequieMa** [comment]
Sorry, I am confused now. 
The sentences should be about "changing variables", right? The Lagrangian is in terms of position and velocity without changing variables, isn't it? L(x, v, t). 
Thus, shouldn't the question be "whether we can write the Lagrangian in terms of position and **momentum**" ? L(x, v, t) -> L(q, p, t)

**Comment by gcarcassi** [comment]
Right, you are looking at it in the opposite way we are looking at it. So, we changed the text to:
![image](https://github.com/user-attachments/assets/6642fd1c-3a34-4212-9c8e-ce65f80adea1)
I think that makes the problem more clear. Does it make sense?
